import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getCookie } from 'cookies-next'
import { useRouter } from 'next/router'
import { verifica } from '../services/user'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>TELA SEGURA</h1>
      </main>
    </div>
  )
}

export const getServerSideProps = async ({req, res}) => {

  try {
    const token = getCookie('authorization', {req, res})
    console.log(token)

    if(!token) throw new Error("Token inválido")

    verifica(token)

    return{
      props: {}
    }
    
  } catch (error) {
    return{
      redirect:{
        permanent: false,
        destination: '/login'
      },
      props: {}
    }
    
    
  }

}